export enum WeatherTypes {
  REQUEST_WEATHER_BEGGIN = 'REQUEST_WEATHER_BEGGIN',
  REQUEST_WEATHER_SUCCESS = 'REQUEST_WEATHER_SUCCESS',
  REQUEST_WEATHER_FAIL = 'REQUEST_WEATHER_FAIL'
}

export enum PageTypes {
  NEXT_PAGE = 'NEXT_PAGE',
  PREV_PAGE = 'PREV_PAGE'
}
